spring:
  data:
    mongodb:
      uri: ${com_camenduru_mongodb_uri}

camenduru:
  scheduler.cron1: ${com_camenduru_scheduler_cron1}
  scheduler.cron2: ${com_camenduru_scheduler_cron2}
  scheduler.default.free.total: ${com_camenduru_scheduler_default_free_total}
  scheduler.default.paid.total: ${com_camenduru_scheduler_default_paid_total}
